name: Feature Request
description: Suggest an idea or enhancement for OWIS
title: "[FEATURE] "
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        Please check the [RFC tracker](../docs/80-RFC/README.md) and [Issue tracker](https://github.com/zaditprodakwah/owis/issues) to ensure your idea hasn't already been proposed.
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when...
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: A clear and concise description of any alternative solutions or features you've considered.
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
